GET http://localhost:4000/user-api/users

###

GET http://localhost:4000/user-api/user/kiran@mail.com

###

POST http://localhost:4000/user-api/create-user
Content-Type: application/json

{
     "username":"bhanu",
     "email":"bhanu@mail.com",
     "age":21
}


###
PUT http://localhost:4000/user-api/modify-user
Content-Type: application/json

{
     "username":"kirabbabu",
     "email":"abcd@mail.com",
     "age":25
}


###
DELETE http://localhost:4000/user-api/delete-user

###
GET http://localhost:4000/abcd


###
GET http://localhost:4000/product-api/products