GET http://localhost:4000/user-api/users

###

GET http://localhost:4000/user-api/user/test2

###

POST http://localhost:4000/user-api/create-user
Content-Type: application/json

{
   "name":"test2",
   "dob":"2023-10-10",
   "designation":"manager",
   "gender":"m"
}


###
PUT http://localhost:4000/user-api/modify-user
Content-Type: application/json

{
   "name":"test2",
   "dob":"2023-10-10",
   "designation":"manager",
   "gender":"m"
}


###
DELETE http://localhost:4000/user-api/delete-user

###
GET http://localhost:4000/abcd


###
GET http://localhost:4000/product-api/products

###
GET http://localhost:4000/project-assignment-api/projectId/200

###
GET http://localhost:4000/project-assignment-api/empId/3

###
GET http://localhost:4000/project-assignment-api/emps-on-bench